[package]
name        = "tmkms"
description = "Tendermint Key Management System"
version     = "0.2.4"
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Ismail Khoffi <Ismail.Khoffi@gmail.com>"]
license     = "Apache-2.0"
homepage    = "https://github.com/tendermint/kms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "ed25519", "kms", "key-management", "yubihsm"]

[workspace]
members = [".", "tendermint-rs"]

[badges]
circle-ci = { repository = "tendermint/kms" }

[dependencies]
abscissa = "0.0.6"
abscissa_derive = "0.0.2"
byteorder = "1.2"
bytes = "0.4"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
lazy_static = "1"
prost-amino = "0.4.0"
prost-amino-derive = "0.4.0"
rand = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
sha2 = "0.8"
signal-hook = "^0.1"
signatory = { version = "0.10", features = ["ed25519"] }
signatory-dalek = "0.10"
signatory-yubihsm = { version = "0.10", optional = true }
subtle-encoding = "0.3"
tendermint = { version = "0.1.5", path = "tendermint-rs" }

[dev-dependencies]
tempfile = "3"

[features]
default = ["softsign", "yubihsm"]
softsign = []
yubihsm = ["signatory-yubihsm/usb"] # USB only for now
yubihsm-mock = ["yubihsm", "signatory-yubihsm/mockhsm"]

# Enable integer overflow checks in release builds for security reasons
[profile.release]
overflow-checks = true
